# Generated by Django 5.0.1 on 2024-01-26 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_designation_section_alter_designation_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(choices=[('doctor', 'doctor'), ('booking', 'booking'), ('lab', 'lab'), ('Default', 'Default'), ('admin', 'admin')], default='Default', max_length=20),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=20)),
                ('designation', models.CharField(choices=[('patient', 'Patient')], default='patient', max_length=20)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_name', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
