# Generated by Django 5.0.1 on 2024-01-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_designation_designation_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
