# Generated by Django 5.0.1 on 2024-01-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_patient_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
