# Generated by Django 5.0.1 on 2024-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_patient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
