# Generated by Django 5.0.1 on 2024-01-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_patient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('consulted', 'consulted'), ('canceld', 'canceld')], default='pending', max_length=20),
        ),
    ]
