# Generated by Django 5.0.1 on 2024-01-27 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_patient_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='section',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AddField(
            model_name='patient',
            name='phno',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('consulted', 'consulted'), ('canceld', 'canceld')], default='pending', max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('section', models.CharField(choices=[('Default', 'Default'), ('cardiology', 'cardiology'), ('oncology', 'oncology'), ('orthopedics', 'orthopedics'), ('Gynacologist', 'Gynacologist')], default='Default', max_length=20)),
                ('token', models.CharField(default='0', max_length=2)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_name', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
