# Generated by Django 5.0.1 on 2024-01-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_patient_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phno',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
