# Generated by Django 5.0.1 on 2024-01-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_patient_phno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='token',
        ),
    ]
