# Generated by Django 5.0.1 on 2024-01-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_consult_token'),
    ]
