# Generated by Django 5.0.1 on 2024-01-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_consult_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='phno',
            field=models.CharField(max_length=10),
        ),
    ]
