# Generated by Django 5.0.1 on 2024-01-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_consult_phno'),
    ]

