# Generated by Django 5.0.1 on 2024-01-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_consult_phno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='phno',
        ),
    ]
