# Generated by Django 5.0.1 on 2024-01-28 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_consult_phno'),
    ]

