# Generated by Django 5.0.1 on 2024-01-28 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_consult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_name', to='app1.patient'),
        ),
    ]
