# Generated by Django 5.0.1 on 2024-01-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_consult_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consult',
            old_name='user',
            new_name='user_id',
        ),
    ]
