# Generated by Django 5.0.1 on 2024-01-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_consult_con_id_prescription_presc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription',
            field=models.FileField(default=2, upload_to='prescription'),
            preserve_default=False,
        ),
    ]
