# Generated by Django 5.0.1 on 2024-01-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_prescription_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='prescription',
        ),
    ]
