# Generated by Django 5.0.1 on 2024-01-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_prescription_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='days',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='routine',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='symptoms',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='tests',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
