# Generated by Django 5.0.1 on 2024-01-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_prescription_days_prescription_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
