# Generated by Django 5.0.1 on 2024-02-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_prescription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='tests',
        ),
        migrations.AddField(
            model_name='consult',
            name='symptoms',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='consult',
            name='tests',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
