# Generated by Django 5.0.1 on 2024-02-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_remove_prescription_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='symptoms',
            field=models.CharField(default='Add', max_length=1000),
        ),
        migrations.AlterField(
            model_name='consult',
            name='tests',
            field=models.CharField(default='Add', max_length=1000),
        ),
    ]
