# Generated by Django 5.0.1 on 2024-02-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_consult_symptoms_alter_consult_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='symptoms',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='consult',
            name='tests',
            field=models.CharField(max_length=1000),
        ),
    ]
